import Foundation
import AppKit

enum PasteboardWriteMarker: Equatable {
    case internalWrite
    case transient
    case autoGenerated
}

final class PasteSynthesizer: @unchecked Sendable {
    func write(
        _ snapshot: ClipboardSnapshot,
        to pasteboard: NSPasteboard = .general,
        markers: [PasteboardWriteMarker] = [.internalWrite]
    ) {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        for rep in snapshot.representations {
            item.setData(rep.data, forType: NSPasteboard.PasteboardType(rawValue: rep.uti))
        }
        for marker in markers {
            switch marker {
            case .internalWrite:
                item.setData(Data("1".utf8), forType: PasteboardMarker.internalWrite)
            case .transient:
                item.setData(Data(), forType: PasteboardMarker.transient)
            case .autoGenerated:
                item.setData(Data(), forType: PasteboardMarker.autoGenerated)
            }
        }
        pasteboard.writeObjects([item])
    }

    func deepCopiedItems(from pasteboard: NSPasteboard = .general) -> [NSPasteboardItem] {
        (pasteboard.pasteboardItems ?? []).map { item in
            let copy = NSPasteboardItem()
            for type in item.types {
                if let data = item.data(forType: type) {
                    // mutableCopy avoids known pasteboard aliasing issues
                    copy.setData((data as NSData).mutableCopy() as! Data, forType: type)
                }
            }
            return copy
        }
    }

    /// Write transformed content, synthesize Cmd+V, optionally restore prior clipboard.
    func writeAndPaste(_ snapshot: ClipboardSnapshot, restoreAfter: Bool = true) {
        let pb = NSPasteboard.general
        let saved = deepCopiedItems(from: pb)
        write(snapshot, to: pb, markers: [.internalWrite, .transient, .autoGenerated])
        let writtenCount = pb.changeCount

        DispatchQueue.main.asyncAfter(deadline: .now() + 0.02) {
            self.synthesizeKey(virtualKey: 0x09, flags: .maskCommand) // V
            if restoreAfter {
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.15) {
                    guard pb.changeCount == writtenCount else { return }
                    pb.clearContents()
                    if !saved.isEmpty {
                        // Re-tag restore so our monitor ignores it.
                        for item in saved {
                            item.setData(Data("1".utf8), forType: PasteboardMarker.internalWrite)
                        }
                        pb.writeObjects(saved)
                    }
                }
            }
        }
    }

    func synthesizeSystemEvent(_ event: ClipboardEvent) {
        switch event {
        case .copy:
            synthesizeKey(virtualKey: 0x08, flags: .maskCommand) // C
        case .cut:
            synthesizeKey(virtualKey: 0x07, flags: .maskCommand) // X
        case .paste:
            synthesizeKey(virtualKey: 0x09, flags: .maskCommand) // V
        case .none:
            break
        }
    }

    func synthesizeKey(virtualKey: CGKeyCode, flags: CGEventFlags) {
        let source = CGEventSource(stateID: .combinedSessionState)
        let keyDown = CGEvent(keyboardEventSource: source, virtualKey: virtualKey, keyDown: true)
        keyDown?.flags = flags
        let keyUp = CGEvent(keyboardEventSource: source, virtualKey: virtualKey, keyDown: false)
        keyUp?.flags = flags
        keyDown?.post(tap: .cghidEventTap)
        keyUp?.post(tap: .cghidEventTap)
    }

    /// Wait until pasteboard changeCount differs from `before`, or timeout.
    func waitForPasteboardChange(before: Int, timeout: TimeInterval = 0.75) async -> Bool {
        let deadline = Date().addingTimeInterval(timeout)
        while Date() < deadline {
            if NSPasteboard.general.changeCount != before {
                return true
            }
            try? await Task.sleep(nanoseconds: 20_000_000)
        }
        return NSPasteboard.general.changeCount != before
    }
}
