import Foundation
import AppKit

// MARK: - Pasteboard markers

enum PasteboardMarker {
    static let internalWrite = NSPasteboard.PasteboardType("com.macv.internal-write")
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
}

// MARK: - Core models

struct PasteboardRepresentation: Codable, Equatable, Sendable {
    let uti: String
    let data: Data
}

enum SnapshotOrigin: Codable, Equatable, Sendable {
    case organicCopy
    case organicCut
    case transformation(scriptID: String)
    case promotion

    var displayName: String {
        switch self {
        case .organicCopy: return "Copy"
        case .organicCut: return "Cut"
        case .transformation(let id): return "Script: \(id)"
        case .promotion: return "Promoted"
        }
    }
}

struct ClipboardSnapshot: Identifiable, Codable, Equatable, Sendable {
    let id: UUID
    let createdAt: Date
    let parentID: UUID?
    let sourceApp: String?
    let origin: SnapshotOrigin
    let representations: [PasteboardRepresentation]

    var previewText: String {
        if let text = preferredPlainText(), !text.isEmpty {
            let trimmed = text
                .replacingOccurrences(of: "\n", with: " ")
                .trimmingCharacters(in: .whitespacesAndNewlines)
            if trimmed.count > 120 {
                return String(trimmed.prefix(117)) + "…"
            }
            return trimmed
        }
        if representations.contains(where: { $0.uti.contains("image") || $0.uti.contains("png") || $0.uti.contains("tiff") }) {
            return "[Image]"
        }
        return "[\(representations.count) type(s)]"
    }

    func preferredPlainText() -> String? {
        preferredPlainTextData().flatMap { String(data: $0, encoding: .utf8) }
    }

    func preferredPlainTextData() -> Data? {
        let stringUTI = NSPasteboard.PasteboardType.string.rawValue
        if let data = representations.first(where: { $0.uti == stringUTI })?.data {
            return data
        }
        // Fall back to any utf8-looking string type
        for rep in representations {
            if rep.uti.contains("text") || rep.uti.contains("utf8") || rep.uti.contains("string") {
                if String(data: rep.data, encoding: .utf8) != nil {
                    return rep.data
                }
            }
        }
        return nil
    }

    static func capture(
        from pasteboard: NSPasteboard,
        origin: SnapshotOrigin,
        parentID: UUID? = nil,
        sourceApp: String? = nil
    ) -> ClipboardSnapshot {
        var reps: [PasteboardRepresentation] = []
        for item in pasteboard.pasteboardItems ?? [] {
            for type in item.types {
                // Skip our markers when capturing for history display payloads;
                // still allow them to be detected via hasMarker helpers.
                if type == PasteboardMarker.internalWrite
                    || type == PasteboardMarker.transient
                    || type == PasteboardMarker.autoGenerated {
                    continue
                }
                if let data = item.data(forType: type) {
                    reps.append(PasteboardRepresentation(uti: type.rawValue, data: data))
                }
            }
        }
        return ClipboardSnapshot(
            id: UUID(),
            createdAt: Date(),
            parentID: parentID,
            sourceApp: sourceApp,
            origin: origin,
            representations: reps
        )
    }

    static func pasteboardHasConcealedContent(_ pasteboard: NSPasteboard) -> Bool {
        pasteboard.types?.contains(PasteboardMarker.concealed) == true
            || pasteboard.pasteboardItems?.contains(where: { $0.types.contains(PasteboardMarker.concealed) }) == true
    }

    static func pasteboardHasInternalWrite(_ pasteboard: NSPasteboard) -> Bool {
        pasteboard.types?.contains(PasteboardMarker.internalWrite) == true
            || pasteboard.pasteboardItems?.contains(where: { $0.types.contains(PasteboardMarker.internalWrite) }) == true
    }

    static func pasteboardHasTransient(_ pasteboard: NSPasteboard) -> Bool {
        pasteboard.types?.contains(PasteboardMarker.transient) == true
            || pasteboard.pasteboardItems?.contains(where: { $0.types.contains(PasteboardMarker.transient) }) == true
    }
}

// MARK: - Bindings

enum ClipboardEvent: String, Codable, CaseIterable, Identifiable, Sendable {
    case paste
    case cut
    case copy
    case none

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .paste: return "Paste"
        case .cut: return "Cut"
        case .copy: return "Copy"
        case .none: return "None (history only)"
        }
    }
}

enum CopyCutMode: String, Codable, CaseIterable, Identifiable, Sendable {
    /// Chord is distinct; transform whatever is already on the pasteboard.
    case transformCurrentClipboard
    /// Intercept Cmd+C/X: synthesize the real copy/cut, then transform.
    case interceptThenTransform

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .transformCurrentClipboard: return "Transform current clipboard"
        case .interceptThenTransform: return "Intercept then transform"
        }
    }
}

struct ShortcutBinding: Codable, Identifiable, Equatable, Sendable {
    let id: UUID
    var scriptID: String
    var event: ClipboardEvent
    var requiresSuppression: Bool
    var copyCutMode: CopyCutMode

    init(
        id: UUID = UUID(),
        scriptID: String,
        event: ClipboardEvent,
        requiresSuppression: Bool? = nil,
        copyCutMode: CopyCutMode = .transformCurrentClipboard
    ) {
        self.id = id
        self.scriptID = scriptID
        self.event = event
        self.requiresSuppression = requiresSuppression ?? (event == .paste)
        self.copyCutMode = copyCutMode
    }
}
